In [1]:
import numpy as np
import json

from pathlib import Path

In [2]:
dict = np.load(Path("D:/WIPAR/repo/results/aggregated_feats.npy"), allow_pickle=True)

dict

{'GN06_2021-01-20_10-15-16': {'anatomical': {'All': {'left_visual': {'moup_timelags~1': array([[[[3.44038991e-01, 3.00906970e-02, 3.75390130e-02, ...,
               2.74694486e-02, 2.77511457e-02, 8.11091072e-03],
              [0.00000000e+00, 3.44038991e-01, 0.00000000e+00, ...,
               0.00000000e+00, 2.25172607e-02, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 3.44038991e-01, ...,
               0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
              ...,
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
               3.44038991e-01, 0.00000000e+00, 0.00000000e+00],
              [0.00000000e+00, 6.81795521e-03, 0.00000000e+00, ...,
               0.00000000e+00, 3.44038991e-01, 0.00000000e+00],
              [0.00000000e+00, 7.64796856e-03, 0.00000000e+00, ...,
               0.00000000e+00, 1.43310684e-03, 3.44038991e-01]]],
     
     
            [[[5.19054328e-01, 2.09550300e-02, 3.04799973e-02, ...,
               2.7145079

In [3]:
import pandas as pd

df = pd.DataFrame.from_dict(dict)

df


GN06_2021-01-20_10-15-16  \
anatomical  {'All': {'left_visual': {'moup_timelags~1': [[...   

                                     GN06_2021-03-26_10-53-05  \
anatomical  {'All': {'left_visual': {'moup_timelags~1': [[...   

                                     GN06_2021-03-29_11-51-27  
anatomical  {'All': {'left_visual': {'moup_timelags~1': [[...

In [ ]:
import pprint
pp = pprint.PrettyPrinter(depth=5,compact=True)
pp.pprint(dict)

In [4]:
feat = "moup_timelags~1"

feats = {}


for session,sdict in dict.items():
    for parcellation,pdict in sdict.items():
        for trials,tdict in pdict.items():
            for condition,cdict in tdict.items():
                feats[condition] = feats.get(condition, {})
                feats[condition][session]=cdict[feat][:,0,:,:]


n_conditions = len(feats)

n_sessions = len(list(feats.values())[0])
t,w,h =  list(list(feats.values())[0].values())[0].shape

feats_array_mean = np.zeros((n_conditions,n_sessions,w,h))
feats_array_std = np.zeros((n_conditions,n_sessions,w,h))

for c , (_, cdict) in enumerate(feats.items()):
    for s, (_, val) in enumerate(cdict.items()):
        feats_array_mean[c,s,:,:] =  np.mean(val,axis=0)
        feats_array_std[c,s,:,:] =  np.std(val,axis=0)
        
#print(feats_array)
pd.DataFrame.from_dict(feats)

print(np.mean(feats_array_mean,axis=1))
                

[[[1.47458455 0.01066415 0.01661765 ... 0.01349726 0.008841   0.01745745]
  [0.01116932 1.47458455 0.01979271 ... 0.0140346  0.01663997 0.00708755]
  [0.01551052 0.0180335  1.47458455 ... 0.01589133 0.01304771 0.01353169]
  ...
  [0.01329106 0.01359091 0.01670249 ... 1.47458455 0.01702197 0.01684798]
  [0.00883829 0.0160903  0.0129465  ... 0.01640012 1.47458455 0.01168408]
  [0.01751023 0.00630079 0.01017025 ... 0.0141226  0.00847986 1.47458455]]

 [[1.7483201  0.00737661 0.0103648  ... 0.01048664 0.00698652 0.01902098]
  [0.00902977 1.7483201  0.0198645  ... 0.01477973 0.01555931 0.0036824 ]
  [0.00938862 0.01730748 1.7483201  ... 0.01605998 0.01282243 0.00521542]
  ...
  [0.0112871  0.0155139  0.01918972 ... 1.7483201  0.01776922 0.012185  ]
  [0.01000552 0.01826865 0.01693982 ... 0.01987393 1.7483201  0.00939489]
  [0.01986119 0.00415268 0.00735246 ... 0.01481467 0.00881913 1.7483201 ]]

 [[1.11371023 0.01299252 0.0248273  ... 0.0237833  0.0139662  0.02383892]
  [0.01272987 1.113710